<<<<<<< HEAD
db.url=jdbc:mysql://localhost:3307/advisora?useSSL=false&serverTimezone=UTC
=======
db.url=jdbc:mysql://localhost:3306/advisora?useSSL=false&serverTimezone=UTC
>>>>>>> gestionUtilisateurs
db.user=root
db.password=
