/*
ADVISORA STRUCTURE COMMENT
 param($m) 'File: ' + ($m.Groups[1].Value -replace '\\','/') 
Role: Service layer: business logic and SQL orchestration
*/
package com.advisora.Services;

import com.advisora.Model.Project;
import com.advisora.enums.ProjectStatus;
import com.advisora.utils.MyConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class ProjectService {
    // Create a new project as a client request.
    // Business rule: every new project starts as PENDING.
    public void add(Project p) {
        validate(p, true);
        p.setStateProj(ProjectStatus.PENDING);
        run(() -> {
            // createdAtProj and updatedAtProj are generated by MySQL NOW().
            String sql = "INSERT INTO Projects (titleProj, descriptionProj, budgetProj, typeProj, stateProj, createdAtProj, updatedAtProj, avancementProj, idClient) VALUES (?, ?, ?, ?, ?, NOW(), NOW(), ?, ?)";
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setString(1, p.getTitleProj());
                ps.setString(2, p.getDescriptionProj());
                ps.setDouble(3, p.getBudgetProj());
                ps.setString(4, p.getTypeProj());
                ps.setString(5, ProjectStatus.PENDING.name());
                ps.setDouble(6, p.getAvancementProj());
                ps.setInt(7, p.getIdClient());
                ps.executeUpdate();
            }
        });
    }

    // Update a project record.
    // updatedAtProj is refreshed automatically in SQL.
    public void update(Project p) {
        validate(p, false);
        run(() -> {
            String sql = "UPDATE Projects SET titleProj=?, descriptionProj=?, budgetProj=?, typeProj=?, stateProj=?, updatedAtProj=NOW(), avancementProj=?, idClient=? WHERE idProj=?";
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setString(1, p.getTitleProj());
                ps.setString(2, p.getDescriptionProj());
                ps.setDouble(3, p.getBudgetProj());
                ps.setString(4, p.getTypeProj());
                ps.setString(5, p.getStateProj().name());
                ps.setDouble(6, p.getAvancementProj());
                ps.setInt(7, p.getIdClient());
                ps.setInt(8, p.getIdProj());
                ps.executeUpdate();
            }
        });
    }

    // Delete a project by id.
    // If DB has FK ON DELETE CASCADE, related decisions are deleted by DB.
    public void delete(int idProj) {
        run(() -> {
            String sql = "DELETE FROM Projects WHERE idProj=?";
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setInt(1, idProj);
                ps.executeUpdate();
            }
        });
    }

    // Read all projects (newest first).
    public List<Project> getAll() {
        return call(() -> {
            String sql = "SELECT * FROM Projects ORDER BY createdAtProj DESC";
            List<Project> list = new ArrayList<>();
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(map(rs));
                }
            }
            return list;
        });
    }

    // Read projects for one specific client only.
    public List<Project> getByClient(int idClient) {
        return call(() -> {
            String sql = "SELECT * FROM Projects WHERE idClient=? ORDER BY createdAtProj DESC";
            List<Project> list = new ArrayList<>();
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setInt(1, idClient);
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        list.add(map(rs));
                    }
                }
            }
            return list;
        });
    }

    // Read one project by title (exact match, case-insensitive).
    public Project getByTitle(String titleProj) {
        if (titleProj == null || titleProj.isBlank()) return null;
        return call(() -> {
            String sql = "SELECT * FROM Projects WHERE LOWER(TRIM(titleProj)) = LOWER(TRIM(?)) LIMIT 1";
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setString(1, titleProj);
                try (ResultSet rs = ps.executeQuery()) {
                    return rs.next() ? map(rs) : null;
                }
            }
        });
    }

    // Read one project by primary key.
    public Project getById(int idProj) {
        return call(() -> {
            String sql = "SELECT * FROM Projects WHERE idProj=?";
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setInt(1, idProj);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        return map(rs);
                    }
                }
            }
            return null;
        });
    }

    // Read all projects sorted dynamically by an allowed column.
    // The sortBy value is whitelisted to avoid SQL injection.
    public List<Project> getSortedProjects(String sortBy) {
        return call(() -> {
            String safeSortBy = switch (sortBy) {
                case "titleProj", "budgetProj", "avancementProj", "createdAtProj" -> sortBy;
                default -> "createdAtProj";
            };

            String sql = "SELECT * FROM Projects ORDER BY " + safeSortBy + " DESC";
            List<Project> list = new ArrayList<>();
            try (Connection cnx = MyConnection.getInstance().getConnection();
                 PreparedStatement ps = cnx.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(map(rs));
                }
            }
            return list;
        });
    }

    // Read only projects waiting for manager decision.
    public List<Project> getPendingProjects() {
        return call(() -> {
            String sql = "SELECT * FROM Projects WHERE stateProj=? ORDER BY createdAtProj ASC";
            List<Project> list = new ArrayList<>();
            try (Connection cnx = MyConnection.getInstance().getConnection(); PreparedStatement ps = cnx.prepareStatement(sql)) {
                ps.setString(1, ProjectStatus.PENDING.name());
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) {
                        list.add(map(rs));
                    }
                }
            }
            return list;
        });
    }

    // Convenience helper bound to current logged-in client.
    public List<Project> getProjectsForCurrentClient() {
        return getByClient(SessionContext.getCurrentUserId());
    }

    // Validate user input before touching database.
    private void validate(Project p, boolean create) {
        if (p == null) throw new IllegalArgumentException("Project null");
        if (p.getTitleProj() == null || p.getTitleProj().isBlank()) throw new IllegalArgumentException("Title required");
        if (p.getBudgetProj() < 0) throw new IllegalArgumentException("Budget >= 0");
        if (p.getAvancementProj() < 0 || p.getAvancementProj() > 100) throw new IllegalArgumentException("Avancement between 0 and 100");
        if (p.getIdClient() <= 0) throw new IllegalArgumentException("idClient invalide");
        if (!create && p.getIdProj() <= 0) throw new IllegalArgumentException("idProj invalide");
    }

    private void run(SqlRun r) {
        try { r.exec(); } catch (SQLException e) { throw new RuntimeException(e); }
    }

    private <T> T call(SqlCall<T> c) {
        try { return c.exec(); } catch (SQLException e) { throw new RuntimeException(e); }
    }

    // Convert one SQL row to Project domain object.
    private Project map(ResultSet rs) throws SQLException {
        Project p = new Project();
        p.setIdProj(rs.getInt("idProj"));
        p.setTitleProj(rs.getString("titleProj"));
        p.setDescriptionProj(rs.getString("descriptionProj"));
        p.setBudgetProj(rs.getDouble("budgetProj"));
        p.setTypeProj(rs.getString("typeProj"));
        p.setStateProj(ProjectStatus.fromDb(rs.getString("stateProj")));
        p.setCreatedAtProj(rs.getTimestamp("createdAtProj"));
        p.setUpdatedAtProj(rs.getTimestamp("updatedAtProj"));
        p.setAvancementProj(rs.getDouble("avancementProj"));
        p.setIdClient(rs.getInt("idClient"));
        return p;
    }
    @FunctionalInterface private interface SqlRun { void exec() throws SQLException; }
    @FunctionalInterface private interface SqlCall<T> { T exec() throws SQLException; }
}
